---
# tasks file for diagnostics

- name: include os-specific variables
  include_vars: "{{ ansible_os_family }}.yml"
  tags: [diagnostics]

- name: install package for debian system
  apt: name={{ item }} state=present
  with_items: diagnostics_packages + os_packages
  when: ansible_os_family=='Debian'
  tags: [diagnostics]

- name: install package for rhel system
  yum: name={{ item }} state=present
  with_items: diagnostics_packages + os_packages
  when: ansible_os_family=='RedHat'
  tags: [diagnostics]
